### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by ajithkpistar** [ajith-kp-1892/Bmsit-Notifier#3]
when ever i open this page it is not going to login

**Comment by tvavinash10** [comment]
what ever code you have put here is chinmay updated code or the old one dude

**Comment by ajithkpistar** [comment]
Id ont knw exactly still i got in one mail and i extracted and pushed here

**Comment by chinmaybhat1** [comment]
This issue no longer exists and the login is working perfectly fine
